### ISSUE TITLE
Our metadata records in violation of GRDC Licence

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#103]
(1) CC BY SA not compatible with paragraph 2.2 and paragraph 2.3 of Dissemination of GRDC-data.
(2) There may also be a problem with stating that GRDC was produced by SWITCH-ON since the original licence requires full citation of the Global Runoff Centre (see annex 2)
See:
http://www.bafg.de/GRDC/EN/01_GRDC/12_plcy/policy_guidelines.pdf?__blob=publicationFile

**Comment by p-a-s-c-a-l** [comment]
@duropa @rcapell @esafa

OK. So what is the correct license to choose for experiment results that are abased on GRDC data?
I think this is an important question for the whole WP3. Can you put this topic on the WP3 discussion list?

**Comment by esafa** [comment]
Well the licence states:

2. Dissemination of GRDC-Data 2.1 GRDC data are available to users free and
unrestricted under the conditions specified in 2.2 to 2.6 below. 2.2
Requests for data must reach the GRDC in written form: letter, facsimile,
telex or email. A proforma is attached for use in this respect (Annex 1).
2.3 The data user agrees in writing that the data received are not
transferred to third parties without the written consent of the GRDC. GRDC
data are released upon identified access, e.g. a signed User Declaration
(Annex 2) 2.4 GRDC data shall not be used for commercial purposes without
the prior consent of Members and other providers of data to the GRDC. The
GRDC will request such consent on behalf of a potential user. 2.5 The data
user agrees that the GRDC may inform the Members and other data providers
of data about the use to which their data have been put and will transfer
the names and addresses of the data users to Members and other data
providers concerned. 2.6 The GRDC makes available subsets of the GRDC
database on request, as stated above. Requests for the entire database or
substantial parts of it cannot be entertained unless consent of the WMO
secretariat has been obta

There is also a signed contract that somebody has to fill in.. in this you
promise the following:

1. The GRDC data are not transferred either in part or total to third
parties or to the general public (e.g. by electronic media), without the
written consent of the GRDC. 2. The data will not be used for commercial
purposes without the written consent of the GRDC. The GRDC itself will
obtain clearance from the respective Members or other data providers prior
to the release of data for commercial purposes. 3. The data set will be not
accessible to unauthorised persons and, after completion of the specified
studies, the data set will be kept separate from the general data
processing facilities on diskette, tape or CD. 4. After completion of the
studies and parts thereof, two copies of the results will be made available
for the GRDC, as well as publications arising from the use of the data set
or parts thereof. 5. In all publications, the source of the data will be
fully cited as: "The Global Runoff Data Centre, D - 56002 Koblenz,
Germany". 6. The GRDC operates on a non-profit basis. In certain cases,
however, the GRDC may charge the data user a nominal amount for data
queries and handling or an amount which has been agreed upon between the
requesting agency and the GRDC prior to data delivery. The undersigned
confirms his/her capacity to pay bills presented by the GRDC for services.


On Thu, Jul 2, 2015 at 7:33 AM, Pascal Dihé <notifications@github.com>
wrote:

> @duropa <https://github.com/duropa> @rcapell <https://github.com/rcapell>
> @esafa <https://github.com/esafa>
>
> OK. So what is the correct license to choose for experiment results that
> are abased on GRDC data?
> I think this is an important question for the whole WP3. Can you put this
> topic on the WP3 discussion list?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/103#issuecomment-117911728>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
> data are not transferred **either in part or total** to third parties

Since we are not re-publishing the GRDC data itself it depends on interpretation of **in part**. Whether the experiments results can be considered *new* data (or the result of a study) that is just based upon GRDC data or a **subset** of GRDC data has to be answered by the scientists that perform the experiments, e.g.@durpa. In the later case we probably have to remove the experiment results from the public SVN Repository and the meta-data from the SIP. 

In any case, scientist that want to have their GRDC-based results published in SIP have to get in contact with GRDC to clarify clear this issue.

**Comment by duropa** [comment]
in our flood experiment, the main objective is to use grdc data to identify the days of flood peaks...so the main outcomes will be a table (for each basin) which will list the periods (days) of flood occurence.

in the current version we are listing also the discharge peak values (so not entire time series), but these can be removed from the results, if it will not fit to the copyright agreement...

(the flood peaks are marked as Qmax and vol in the files)...

 
in the second part of the experiment (the new results), we assigned to each flood peak some simulated values from ehype model...so this should be ok, in terms of the agreement...

 
so i see just one problematic part- if qmax (discharge peaks) can be published or not...if not, not a problem for the experiment...we just need to remove it from the results in sip...

 
does it clarify the question?

 
cheers

d.

 
 

 
-----Original message-----

**Comment by esafa** [comment]
Results may be published according the the GRDC licence. The licence does
NOT state any issues with publishing new results derived from the original
GRDC data but they do request copies of any results sent to them. IMO, a
simple extraction of a value for an individual station would arguable not
be a new result (although the licence is not clear on that point so even
that could be admissable). Calculating maximum would in my opinion be an
aggregated result.

Do you want me to run this by our lawyer?

//eF



On Thu, Jul 2, 2015 at 12:09 PM, duropa <notifications@github.com> wrote:

> in our flood experiment, the main objective is to use grdc data to
> identify the days of flood peaks...so the main outcomes will be a table
> (for each basin) which will list the periods (days) of flood occurence.
>
> in the current version we are listing also the discharge peak values (so
> not entire time series), but these can be removed from the results, if it
> will not fit to the copyright agreement...
>
> (the flood peaks are marked as Qmax and vol in the files)...
>
>
> in the second part of the experiment (the new results), we assigned to
> each flood peak some simulated values from ehype model...so this should be
> ok, in terms of the agreement...
>
>
> so i see just one problematic part- if qmax (discharge peaks) can be
> published or not...if not, not a problem for the experiment...we just need
> to remove it from the results in sip...
>
>
> does it clarify the question?
>
>
> cheers
>
> d.
>
>
>
>
>
>
> -----Original message-----
> From:Pascal Dihé <notifications@github.com>
> Sent:Thu 02-07-2015 11:07
> Subject:Re: [sip-html5] Our metadata records in violation of GRDC Licence
> (#103)
> To:switchonproject/sip-html5 <sip-html5@noreply.github.com>;
> CC:Juraj Parajka <parajka@hydro.tuwien.ac.at>;
>
>
> data are not transferred either in part or total to third parties
>
>
>
> Since we are not re-publishing the GRDC data itself it depends on
> interpretation of in part. Whether the experiments results can be
> considered new data (or the result of a study) that is just based upon GRDC
> data or a subset of GRDC data has to be answered by the scientists that
> perform the experiments, e.g.@durpa. In the later case we probably have
> to remove the experiment results from the public SVN Repository and the
> meta-data from the SIP.
>
>
>
> In any case, scientist that want to have their GRDC-based results
> published in SIP have to get in contact with GRDC to clarify clear this
> issue.
>
>
>
> —
> Reply to this email directly or view it on GitHub.
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/103#issuecomment-117989467>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by duropa** [comment]
dear esa,

a general clarification about the grdc licence would be useful...i think these data are/will be used not only in our grdc experiment.

some repurposing of this dataset (e.g. derived basin boundaries for the grdc stations, or some basin characteristics - mean elevation, land use, etc) could be an attractive datasource in our sip...

 
cheers

d.


 
-----Original message-----

**Comment by p-a-s-c-a-l** [comment]
> Do you want me to run this by our lawyer?

Perhaps It would be easier to ask the the GRDC directly, i.e. sent them some sample datasets and a link to project website?

**Comment by esafa** [comment]
We can do both .. but first check with SMHI lawyer.. If he says we are doing something wrong, we can amend those things and then ask GRDC.

**Comment by esafa** [comment]
The views of the SMHI lawyer.

(1) Obviously, SWITCH-ON may not republish any GRDC data without written agreement with GRDC.
(2) Processing we do on the data does not diminish the legal rights of the provider. This means that e.g. monthly maximum or average of their time series may not be published even if it is not a pure republishing. You can publish results if you have a written agreement with GRDC.
(3) If the data is heavily processed and combined with other data the rights of GRDC is diminished.. this is the famous "grey-zone" subject to legal battles.
(4) If the data is so much processed that you cannot say anything about the original GRDC data then you may publish it. E.g. you may publish MD5-signatures of the GRDC data. Another example could be the EHype results where 60 datasets are combined and processed to produce the results.

**Comment by p-a-s-c-a-l** [comment]
GRDC  datasets removed. See https://github.com/switchonproject/cids-custom-switchon-server/issues/42#issuecomment-120331035
