### ISSUE TITLE
Unnecessary inputbox to define max search results.

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#104]
The default search returns 10 values.. maximum is 25 values.

A box to input number of search results makes sense when you have thousands of results.. but with such a small range (10-25) to choose from It would be much better to just skip this box completely. 

Either the user has a very precise query and he will get the one dataset he/she is looking for.
or.. the user is "browsing" and has a very vague idea of what data he might be able to use and in this case 15 more results will not help him.

**Comment by p-a-s-c-a-l** [comment]
OK, I'll remove the box from the options. For "power users" there's still the possibility to manually set the number of results by typing e.g. `limit:"100"`.

**Comment by p-a-s-c-a-l** [comment]
Resolved in #109 and available in snapshot release: http://switchon.cismet.de/sip-snapshot
