### ISSUE TITLE
Search returning many matches but no "next" button

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#105]
When testing I found that most searches return more than 25 results.  But there is no way to scroll among the results to refine the search. Nor Is there a "NEXT" button...

This limits the usefulness for "browsing your open data". 

Suggestion

First search would give 25 rows.. 
Add a NEXT-button (Ebay-style) so pressing next gets the next 25 rows but keeps the old rows in the browserwindow (total of 50 rows with a scrollbar).
Subsequent pressing on Next retrieves 25 rows each.

**Comment by p-a-s-c-a-l** [comment]
The *next* button is hidden in the tools menu. If tools are always shown when search results are available (https://github.com/switchonproject/sip-html5/issues/108), it should be more visible.

![next-button](https://cloud.githubusercontent.com/assets/1788226/8516503/3b9241fe-23b5-11e5-9989-2ff670895708.png)

Regarding incremental results: I like the idea, but this is this is major change. I'll keep this for later.

**Comment by p-a-s-c-a-l** [comment]
Resolved in #109 and available in snapshot release: http://switchon.cismet.de/sip-snapshot
