### ISSUE TITLE
Colourblind people dont see red frames (max search results)

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#106]
10% of the male population is red/green-colourblind (me included). They have problems seeing when the frame of the max search result box changes colour (number less than 26 = green, 26 and above =red).

note: see other issue. We should probably not have this box at all since the range is so limited (see other issue reported). If the box is removed we dont need to fix it.

**Comment by p-a-s-c-a-l** [comment]
OK. See https://github.com/switchonproject/sip-html5/issues/104#issuecomment-118736402

**Comment by p-a-s-c-a-l** [comment]
Resolved in #109 and available in snapshot release: http://switchon.cismet.de/sip-snapshot
