### ISSUE TITLE
Access conditions and Access functions are hidden 

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#107]
After a freetext search (e.g. "GRDC") you get a preview mode listing of matches.
on the left side there are two "links": Accessconditions and Access functions. 

These are not expanded by default which means a first time user will not understand what they mean... 

It would be much clearer for the first time user to have these two items expanded so you can see that the accessfunctions are "download", "order", "service"... And you can see that the conditions are CCBYSA..

There is no issue with having room for these on the left side.. and If there is a problem with room we would need a scrollbar anyway.

**Comment by p-a-s-c-a-l** [comment]
OK, I'll expand the lists by default. 
Btw, in addition to access functions & conditions,  I could also add X-CUAHSI keywords if you think this would be useful.

**Comment by esafa** [comment]
Lets ask @rcapell and the others on if they think it will be useful later.

On Mon, Jul 6, 2015 at 8:26 AM, Pascal Dihé <notifications@github.com>
wrote:

> OK, I'll expand the lists by default.
> Btw, in addition to access functions & conditions, I could also add
> X-CUAHSI keywords if you think this would be useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/107#issuecomment-118739878>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
Resolved in #109 and available in snapshot release: http://switchon.cismet.de/sip-snapshot
