### ISSUE TITLE
TOOLS button unnecessary

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#108]
For first time users, the option "LIST" and "MAP" are very clear but the "TOOL"-button is less clear.

In the dev release, when doing a freetext search (e.g. "GRDC"), the toolmenu is opened by default. 

So the only function of the button is to close the TOOL frame.  Why would anybody want to close it? If you have a very old screen with 800x600 resolution it would make sense to be able to close it but with modern computers screen-width is not an issue.

I suggest we remove the TOOL button and keep the TOOL-frame open on the left side at all times.

**Comment by p-a-s-c-a-l** [comment]
Resolved in https://github.com/switchonproject/sip-html5/commit/04c9836b6f65fda6e932ac93aec115b3d02ab338 and changed in snapshot release: http://switchon.cismet.de/sip-snapshot/
