### ISSUE TITLE
New Beta Release for CUAHSI Workshop

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/sip-html5#110]
Deploy new Beta Release at http://www.water-switch-on.eu/sip-webclient/sip-beta for CUAHSI Workshop. See https://github.com/switchonproject/sip-html5/issues/99

**Comment by esafa** [comment]
BYOD production instance is down.

**Comment by p-a-s-c-a-l** [comment]
yes. deltares server maintenance reboot strikes again :(
have to check why the SIP services didn't start properly.

**Comment by esafa** [comment]
Ok. I think the CUAHSI meeting is not this week. Do you know the dates?
it might be this meeting https://www.cuahsi.org/HydroInfo2015 that runs July
15-17, 2015.



On Tue, Jul 7, 2015 at 9:58 AM, Pascal Dihé <notifications@github.com>
wrote:

> yes. deltares server maintenance reboot strikes again :(
> have to check why the SIP services didn't start properly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/110#issuecomment-119110093>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
New Release is available: https://github.com/switchonproject/sip-html5/releases/tag/sip-v0.6-beta

**Comment by p-a-s-c-a-l** [comment]
done
