### ISSUE TITLE
option to clear results

### ISSUE THREAD

**Issue by rcapell** [switchonproject/sip-html5#112]
Is there a way to clear results from the sip interface? If I draw a polygon or select a keyword, the list of results and map markers do not disappear when I delete the rectangles from the query line.
Results will be replaced if I form a new query, but I find it confusing.

**Comment by p-a-s-c-a-l** [comment]
No there is currently no possibility to clear the results, but I could add this function. 

I wouldn't however place that functionality on the search box because this would lead to user interaction inconsistencies. E.g. what happens if there are multiple search filters in the box and the user just deletes one of them? Clear partial results (iIn fact, this would perform a new search) or nothing?

**Comment by rcapell** [comment]
That is true, would be confusing.

I would be happy with any solution that allows to clear everything
 and get back to a clean start condition.

**Comment by esafa** [comment]
reload the entire page in browser should work


On Fri, Jul 10, 2015 at 11:58 AM, rcapell <notifications@github.com> wrote:

> That is true, would be confusing.
>
> I would be happy with any solution that allows to clear everything
> and get back to a clean start condition.
>
> On Fri, Jul 10, 2015 at 7:45 AM, Pascal Dihé <notifications@github.com>
> wrote:
>
> > No there is currently no possibility to clear the results, but I could
> add
> > this function.
> >
> > I wouldn't however place that functionality on the search box because
> this
> > would lead to user interaction inconsistencies. E.g. what happens if
> there
> > are multiple search filters in the box and the user just deletes one of
> > them? Clear partial results (iIn fact, this would perform a new search)
> or
> > nothing?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/switchonproject/sip-html5/issues/112#issuecomment-120235405
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/112#issuecomment-120330968>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
> reload the entire page in browser should work

Yes, I does. @rcapell Do you think that this is sufficient?
