### ISSUE TITLE
link from result marker on map to data description

### ISSUE THREAD

**Issue by rcapell** [switchonproject/sip-html5#113]
Draw a polgon to get results (see screenshot).
Today there is no way to get from the map marker to the corresponding result list item (or am i missing something?).
For point results, there is some mouse-hover information. For polygons, there is nothing, and I don't see how I can get to the list result, e.g. the Lithuania data set in the screenshot. This is especially problematic if there are many results from my query. Ideally, a click on the result would take me to the detailed description.
![screenshot_sip_mapresult](https://cloud.githubusercontent.com/assets/6536193/8600871/ab375b60-2668-11e5-83df-a5f1cc6c0ea0.png)

Don't know if bug or enhancement...

**Comment by p-a-s-c-a-l** [comment]
Yes, makes sense to add this functionality. I would say, it's an enhancement. :)

**Comment by p-a-s-c-a-l** [comment]
resolved in #109
