### ISSUE TITLE
Request from Berit

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#116]
När det står "switchon.wm" som "point of contact" så ska det stå "Point of contact for metadata".

Translated:

When it says "switchon.wm" as "point of contact" it should instead say "Point of contact for metadata".

**Comment by p-a-s-c-a-l** [comment]
Contact information will be hidden anyway in next release, see https://github.com/switchonproject/cids-custom-switchon/issues/137

**Comment by esafa** [comment]
that solves it.


On Fri, Jul 10, 2015 at 12:26 PM, Pascal Dihé <notifications@github.com>
wrote:

> Contact information will be hidden anyway in next release, see
> switchonproject/cids-custom-switchon#137
> <https://github.com/switchonproject/cids-custom-switchon/issues/137>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/116#issuecomment-120361080>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
done
