### ISSUE TITLE
spatial search for smaller areas (part of country) not working

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#118]
With intersect you get the worldbox is ruining the search result (false matches)
With encloses you dont get anything.

Solution: clean metadata, and to modify tool to search only multipoint, multipolygon, and raster bounding boxes and image bounding boxes.   The remaining bounding boxes only give a lot of false matches in spatial search

**Comment by esafa** [comment]
Somebody has to tag the non-covering bounding boxes (e.g. bounding boxes for many observation stations)

**Comment by p-a-s-c-a-l** [comment]
New geo search implemented and now available in beta release: http://www.water-switch-on.eu/sip-webclient/sip-beta/

![clc](https://cloud.githubusercontent.com/assets/1788226/9408553/39fd4a36-4814-11e5-9019-505bb154f8b7.gif)
