### ISSUE TITLE
excel extract

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#119]
See also https://github.com/switchonproject/cids-custom-switchon/issues/139

We want a function in the wizard to extract all the data as an excel or csv file (with all basic attributes = the basic profile in the wizard). This is essential during the testing phase of the data to see that the number of datasets in the database matches the data in the batches. The extraction can also be used for other statistical purposes and to facilitate finding errors in data entries.

The excel file will contain approx 9000 resources. We need to start testing 3rd of August.

**Comment by p-a-s-c-a-l** [comment]
Why should we put such a functionality that is only needed for internal testing in the public client? Neither the HTML client nor the REST API  have been designed to support the export of the whole Meta-Data Repository.

**Comment by esafa** [comment]
It is not only needed for internal testing... Basically, all scientist can
use excel (but all cannot use GIS). An export facility would allow the user
to do other forms of filtering, summing, sorting, extractions that we dont
have time to implement.

The design does not have be changed. It is just one button that does a
csv-file download. Should not be more than some 50 rows of code.

But sure.. we can have it outside the HTML5-client.. Put the button on the
SIP-page in the portal instead if that is easier.
As long as the functionality is easily available for scientists.

//esa





On Sun, Jul 12, 2015 at 3:10 PM, Pascal Dihé <notifications@github.com>
wrote:

> Why should we put such a functionality that is only needed for internal
> testing in the public client? Neither the HTML client nor the REST API have
> been designed to support the export of the whole Meta-Data Repository.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/119#issuecomment-120720205>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
> some 50 rows of code.

No. As I wrote, the **public** REST API hasn't been designed to support the export of the whole Meta-Data Repository. This is a major change.

Btw, It seems that we abandoned the user stories approach? 

@remko @rcapell @duropa
Is there need for a such a functionality to extract **all** meta-data as an excel or csv file?

**Comment by duropa** [comment]
sorry, for asking. does this relate to individual sip search results or the whole repository?
i'm not sure if i would be interested to export all the repository, but for some of my individual sip searches it seems to be important (to me).
d.

**Comment by esafa** [comment]
Yes you are right Pascal. It is the user-story group that decides what is
needed for the BYOD.

According to the plan we are "soon" closing the active part of development
on the BYOD. This is the opportunity to call for new features. Since we
need the csv-export for administration and testing anyway, I thought we
could make the full excelsheet  available for the scientists (approx 13000
rows of metadata). But there is no motivation to make the excelsheet
available if the scientists already are happy with the current search and
find features.

Cheers,
//Esa




On Mon, Jul 27, 2015 at 6:34 AM, Pascal Dihé <notifications@github.com>
wrote:

> some 50 rows of code.
>
> No. As I wrote, the *public* REST API hasn't been designed to support the
> export of the whole Meta-Data Repository. This is a major change.
>
> Btw, It seems that we abandoned the user stories approach?
>
> @remko <https://github.com/remko> @rcapell <https://github.com/rcapell>
> @duropa <https://github.com/duropa>
> Is there need for a such a functionality to extract *all* meta-data as an
> excel or csv file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/119#issuecomment-125084723>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)
