### ISSUE TITLE
group single data sets to collections

### ISSUE THREAD

**Issue by rcapell** [switchonproject/sip-html5#120]
If I search for data which is published in separate sets for each time step, e.g. the "GLDAS-1, 0.25 degree" evaporation flux data set, there will be one separate result for each set (i.e. time step) in the byod today. This could be hundreds of hits describing essentially the same data. They also obscure other search results which might appear on page 100something in the result list. 
Such sets should be grouped into collections, e.g. as an expandable list in the search results, so that I can see that they all describe the same data, and also so that I can also see other results which describe different data sets.

**Comment by p-a-s-c-a-l** [comment]
See my answer regarding problems with expandable lists in search results: https://github.com/switchonproject/sip-html5/issues/114#issuecomment-120721661

**Comment by p-a-s-c-a-l** [comment]
As intermediate solution I enabled the *collections* filter, now you can exclude such datasets from search results:

![collections](https://cloud.githubusercontent.com/assets/1788226/9409674/6bec9882-481c-11e5-9c40-a067c06201d1.gif)

Already available in SIP Beta Version: http://www.water-switch-on.eu/sip-webclient/sip-beta/

**Comment by esafa** [comment]
nice. it is consistent with the other "exclusions" you can do...

On Fri, Aug 21, 2015 at 3:53 PM, Pascal Dihé <notifications@github.com>
wrote:

> As intermediate solution I enabled the *collections* filter, now you can
> exclude such datasets from search results:
>
> [image: collections]
> <https://cloud.githubusercontent.com/assets/1788226/9409674/6bec9882-481c-11e5-9c40-a067c06201d1.gif>
>
> Already available in SIP Beta Version:
> http://www.water-switch-on.eu/sip-webclient/sip-beta/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/120#issuecomment-133431544>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by rcapell** [comment]
Thanks. This solution works for me, but I don't know if this is obvious to users of the portal. @esafa this might be good to test with reference group users before we accept this as a solution?
