### ISSUE TITLE
Remove temporal extent from search results

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/sip-html5#129]
When searching after resources in the BYOD one of the columns show temporal extent. A majority of the datasets do not have this information and thus the column only shows '-'. Since this information haven't been requested it should be removed from the interface.

![temporal extent](https://cloud.githubusercontent.com/assets/8414617/16302564/23b70f08-394c-11e6-8ece-2be1175f349c.png)

**Comment by p-a-s-c-a-l** [comment]
done
