### ISSUE TITLE
Missing topic category

### ISSUE THREAD

**Issue by Bastviken** [switchonproject/sip-html5#130]
Some resources are registered with "environment" as topic category. However, when searching for the "environment" in the inspire topic categories list the word does not exist. I would expect "environment" to be included in that list so that the topic could be searched on its own.

![missing topic category](https://cloud.githubusercontent.com/assets/20067109/16373558/25d5e782-3c53-11e6-83a9-d162e4c654f9.png)

**Comment by esafa** [comment]
Inspire topic is defined by EU. We cant add items to this list.

Close.
Den 27 jun 2016 10:39 skrev "Bastviken" <notifications@github.com>:

**Comment by p-a-s-c-a-l** [comment]
Added "environment" to the list as it is a valid topic category according to http://inspire.ec.europa.eu/metadata-codelist/TopicCategory
