### ISSUE TITLE
Minor issue - Polyline color hard to spot

### ISSUE THREAD

**Issue by Bastviken** [switchonproject/sip-html5#133]
For resources visualized with polylines it seems like various colors are used (see screen shots below). Polylines in orange are sometimes hard to see. As a user I would expect that polylines would blue, just as the polygons, or at least be easy to spot on the basemap.
![polylines_various_colors](https://cloud.githubusercontent.com/assets/20067109/17659219/69aebe4e-62d1-11e6-9975-7f2104f54de0.png)
![faults_various_colors](https://cloud.githubusercontent.com/assets/20067109/17659226/73c6fa68-62d1-11e6-9dca-ccbdf75a085a.png)

**Comment by p-a-s-c-a-l** [comment]
Polylines are now rendered in blue:

![sld](https://cloud.githubusercontent.com/assets/1788226/17726021/4057b0c0-6450-11e6-877e-e6caedfb9610.png)
