### ISSUE TITLE
User story no. 3

### ISSUE THREAD

**Issue by rcnijzink** [switchonproject/sip-html5#26]
As a hydrologist, I need to see the all Cuahsi keywords (column B to D) for each result, so I get all keyword information which is currently missing.

**Comment by schlob** [comment]
I presume this means that you want to see all keywords that have been attached to a specific resource
(in the result list)?

**Comment by p-a-s-c-a-l** [comment]
This mock-up shows how keywords assigned to resources can be presented in the table of results:

![user-story-no-3](https://cloud.githubusercontent.com/assets/1788226/5976036/98911c60-a889-11e4-979d-2ab8bac818a2.png)

**Comment by p-a-s-c-a-l** [comment]
Since resources contain many different keywords, not only CUASHI keywords, we can also add the possibility to highlight CUASHI keywords as shown in the screen shot below:

![highlight-keywords](https://cloud.githubusercontent.com/assets/1788226/5981576/8284f694-a8bb-11e4-88c5-8402891b95cd.png)

**Comment by rcapell** [comment]
Thanks for implementing this, you never got any feedback from us test users. 
Remko and I just discussed this and we would like to see only the CUAHSI keywords in this column, since it is not clear how the other keywords came about and they don't all seem to be useful/interpretable (many acronyms in there).

**Comment by p-a-s-c-a-l** [comment]
O.K. We can change that behaviour but be aware that the keywords list will be empty until somebody actually tags the resources with CUASHI keywords. Because at the moment we show the general keywords and just highlight those that "coincidentally" match CUASHI keywords.

**Comment by esafa** [comment]
We can add the CUASHI keywords to a limited set of datasets so the search
will not be empty. During the summer we will have someone doing the
complete set.


On Mon, Feb 9, 2015 at 7:05 PM, Pascal Dihé <notifications@github.com>
wrote:

> O.K. We can change that behaviour but be aware that the keywords list will
> be empty until somebody actually tags the resources with CUASHI keywords.
> Because at the moment we show the general keywords and just highlight those
> that "coincidentally" match CUASHI keywords.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/26#issuecomment-73557719>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
Closed
