### ISSUE TITLE
User story René 01

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/sip-html5#4]
![*René](https://avatars3.githubusercontent.com/u/9919?v=3&s=64) **René**: 
> As an environmental scientist who does topical research using multivariate data, I would like to search by keyword for (links to) data listed in the SIP, so that I can immediately evaluate if there is all the data available for my project, as opposed to having to search for each class of data separately.

**Comment by schlob** [comment]
I have to admit that I do not get the point. This is due to my ignorance regarding your science:-)
First I do not really understand "topical research using multivariate data" and whether itis relevant for the user story. 
Second, The rest is not clear to me either:-)  A keyword is a predefined term that can be added (like a sticky) to something (e.g. data). So a list of predefined keywords is supposed to deliver all the input (and only that) you need for your experiment? Please elaborate.

**Comment by rcapell** [comment]
I try to give an example:
Suppose I would like to do a study on water residence times (e.g. how long a volume of water takes to pass through a catchment). These type of studies can be done using various measures parameters, e.g. chemical compounds or isotopes, as tracer of mixing properties within the catchment.
Because I could choose from a multitude of parameters and maybe could accept to mix several of them, e.g. in a comparison study, i would like to be able to search for the whole group of parameters and not one by one (risking to miss one). So, for instance, i could maybe search for the keyword "aquatic chemistry" and get results on, say, silica and chloride measurements, which both would be of use for my study.
Another example could be that i would be interested in all sorts of information regarding "agriculture", and that could be diverse data such as crop types, stock densities, or fertilizer amounts.
Last example: I could be interested in any parameter related to snow, that could be a satellite product giving fraction snow cover, a time series of snow depth, or a time series of snow water equivalent. 
A follow-up question would be how these keywords are selected. They could also be use of a hierarchical order, e.g. a keyword assignment of "nutrient" would also assign a parent keyword, e.g. "chemistry".

**Comment by esafa** [comment]
just a note...

cuahsi project has indeed a spreadsheet with hierarchical topics. have a
look at the inspirationlink to Cuashi and see if this something similar to
the grouping of parameters into aquatic chemistry mentioned by rene.
 Den 15 jan 2015 17:47 skrev "rcapell" <notifications@github.com>:

**Comment by rcapell** [comment]
ah, very good, I intended to mention Cuahsi, but forgot it in the end. Here
is the link to their homepage for reference:
https://www.cuahsi.org/

**Comment by p-a-s-c-a-l** [comment]
I couldn't find this hierarchical topics list or the search user 
interface where you can select hierarchical topics on the Cuahsi 
website. Can you please provide a direct link?

Am 16.01.2015 um 09:54 schrieb rcapell:
> ah, very good, I intended to mention Cuahsi, but forgot it in the end. 
> Here
> is the link to their homepage for reference:
> https://www.cuahsi.org/

**Comment by p-a-s-c-a-l** [comment]
Hierarchical keywords are not supported by the current data model (SIM) nor is there any resource in the meta-data repository with hierarchical keywords. Moreover, the classifications (inspire topic categories and INSPIRE themes 1.0)  that have been selected for the basic ISO 19115 meta data profile do not employ any hierarchy.  On the other hand, if for example  "say"-, "silica"- or "chloride"-resources are also tagged with "aquatic chemistry" a search for "aquatic chemistry" keyword will of course find all of those resources although there is no parent-chlid relationship between those keywords on information model level! So there's not really a need to change the SIM but more an issue how the GUI presents the available/selectable keywords to he user. Btw, I wouldn't recommend to change the SIM since introducing a hierarchy in the SIM classes "Tag" and "Tags Group" would be a rather drastic change that affects many existing components (CSW Mapping, Expert GUI Renderers, Editors and Wizards).

This user story depends also on the quality of meta-data. What we have to do is to identify a suitable classification (e.g. the cuashi list ) and tag relevant resources according to this classification. This could be a task for a meta-data summerworker. Assigning new keywords to resources is not a complicated task and can be done with help of the Expert GUI.  If resources are properly tagged also a basic ("flat") keyword selection GUI element like this one would support this user story:

![uc001-040-search-filter-keyword](https://cloud.githubusercontent.com/assets/1788226/5774154/2eee1dc2-9d6b-11e4-95d8-f2b789bb4204.png)

GUI elements for hierarchical selection of keywords could be implemented too, but only after the basic keyword selection is ready and suitable meta-data is available.

> I try to give an example:
> Suppose I would like to do a study on water residence times (e.g. how long a volume of water takes to pass through a catchment). These type of studies can be done using various measures parameters, e.g. chemical compounds or isotopes, as tracer of mixing properties within the catchment.
> Because I could choose from a multitude of parameters and maybe could accept to mix several of them, e.g. in a comparison study, i would like to be able to search for the whole group of parameters and not one by one (risking to miss one). So, for instance, i could maybe search for the keyword "aquatic chemistry" and get results on, say, silica and chloride measurements, which both would be of use for my study.
> Another example could be that i would be interested in all sorts of information regarding "agriculture", and that could be diverse data such as crop types, stock densities, or fertilizer amounts.
> Last example: I could be interested in any parameter related to snow, that could be a satellite product providing fraction of snow cover, a time series of snow depth, or a time series of snow water equivalent.
> A follow-up question would be how these keywords are selected. They could also be ordered in a hierarchy, e.g. a keyword assignment of "nutrient" would also assign a parent keyword, e.g. "chemistry".

**Comment by esafa** [comment]
Here is a direct link to the ontology (actually it was someone in the
consortium that pointed me to this resource).

http://his.cuahsi.org/ontologyfiles.html

Before we embark in this direction make sure this is really is the so
useful that it deserves to be the first userstory to tackle.

Cheers,
//Esa


On Fri, Jan 16, 2015 at 9:54 AM, rcapell <notifications@github.com> wrote:

> ah, very good, I intended to mention Cuahsi, but forgot it in the end.
> Here
> is the link to their homepage for reference:
> https://www.cuahsi.org/
>
> On Thu, Jan 15, 2015 at 9:34 PM, esafa <notifications@github.com> wrote:
>
> > just a note...
> >
> > cuahsi project has indeed a spreadsheet with hierarchical topics. have a
> > look at the inspirationlink to Cuashi and see if this something similar
> to
> > the grouping of parameters into aquatic chemistry mentioned by rene.
> > Den 15 jan 2015 17:47 skrev "rcapell" <notifications@github.com>:
> >
> > > I try to give an example:
> > > Suppose I would like to do a study on water residence times (e.g. how
> > long
> > > a volume of water takes to pass through a catchment). These type of
> > studies
> > > can be done using various measures parameters, e.g. chemical compounds
> > or
> > > isotopes, as tracer of mixing properties within the catchment.
> > > Because I could choose from a multitude of parameters and maybe could
> > > accept to mix several of them, e.g. in a comparison study, i would
> like
> > to
> > > be able to search for the whole group of parameters and not one by one
> > > (risking to miss one). So, for instance, i could maybe search for the
> > > keyword "aquatic chemistry" and get results on, say, silica and
> chloride
> > > measurements, which both would be of use for my study.
> > > Another example could be that i would be interested in all sorts of
> > > information regarding "agriculture", and that could be diverse data
> such
> > as
> > > crop types, stock densities, or fertilizer amounts.
> > > Last example: I could be interested in any parameter related to snow,
> > that
> > > could be a satellite product giving fraction snow cover, a time series
> > of
> > > snow depth, or a time series of snow water equivalent.
> > > A follow-up question would be how these keywords are selected. They
> > could
> > > also be use of a hierarchical order, e.g. a keyword assignment of
> > > "nutrient" would also assign a parent keyword, e.g. "chemistry".
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/switchonproject/sip-html5/issues/4#issuecomment-70116887>
>
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/switchonproject/sip-html5/issues/4#issuecomment-70156544>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/4#issuecomment-70224976>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by rcapell** [comment]
thanks. No, I am quite sure that this one will not be the first issue...

**Comment by schlob** [comment]
:see_no_evil:
