### ISSUE TITLE
User story no 5

### ISSUE THREAD

**Issue by rcapell** [switchonproject/sip-html5#40]
This is a candidate, not agreed on yet. Noted att Saarbruecken meeting.

As a hydrologist looking for data in the SIP, I would like to perform a free text search on all metadata content in addition to keyword search, so I can use the information included in description and non-CUAHSI keywords to increase the likelihood that I find the data I need.

René would like to see this, @rcnijzink and @duropa, please confirm if you want this implemented as well.

**Comment by rcnijzink** [comment]
Yes, I agree with this user story

**Comment by duropa** [comment]
yes, agree...(to wnat to see it implemented)

d.


 
-----Original message-----

**Comment by p-a-s-c-a-l** [comment]
Yes, this will be implemented.

**Comment by p-a-s-c-a-l** [comment]
@rcapell @rcnijzink @duropa 

This user story is implemented in the new release:
https://github.com/switchonproject/sip-html5/releases/tag/sip-v0.3-alpha

![sip-alpha-v0 3](https://cloud.githubusercontent.com/assets/1788226/6354702/7669dc7c-bc51-11e4-83a9-19295b6cb4f5.gif)
