### ISSUE TITLE
Make new Releases

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/sip-html5#49]
Make new Release of SIP HTML5 Alpha Client and replace the [current version](https://github.com/switchonproject/cids-custom-switchon/wiki/SIP-Releases#sip-html5-client) on deltares server.

**Make DEV Builds available on cismet servers.**

**Comment by p-a-s-c-a-l** [comment]
Consider also Berit's comment in the new release: *"Make all fields in the search function that are not tagged with a dataset GREY and not clickable – this will create less confusion among external users."* -> Make CUASHI Keywords grey

**Comment by p-a-s-c-a-l** [comment]
**DEVelopment Builds are available here:** http://switchon.cismet.de/sip-snapshot

**Comment by duropa** [comment]
the sip-snapshot is nice, however the download of found dataset is confusing (i searched for area, found 1 dataset, clicked download, a window "Downloads of Subbasin division" appeared, but the button OK does not mean download....).can we have here two buttons (e.g. close and download)?

**Comment by p-a-s-c-a-l** [comment]
Thanks! The download behaviour will change. [User Story no. 6](https://github.com/switchonproject/sip-html5/issues/43) is not implemented yet (https://github.com/switchonproject/sip-html5/issues/50).

**Comment by p-a-s-c-a-l** [comment]
done
