### ISSUE TITLE
Import list of D4.3 metadata into SIP

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#53]
This is due in April and is not related to WP3 at all.  Most likely, this can be entered with the existing metadata wizard (by an "expert").  For now, it has low priority.
 
WP4 Task 4.2:  The input data of all 14 products will be collected and put into SIP. 

The data is collected in spreadsheet with the attributes agreed in saarbrucken with only one additional element: linage (to describe the preparations and adaptations made before the input data could be used by the product).

**Comment by p-a-s-c-a-l** [comment]
O.K. Probably we have to introduce an additional attribute "main category" in order to support Berit's suggestion:

> *"Could there also be a list of available metadata, sorted according to topics - for the user to get an overview of what is in there? (I guess Emmas Metadata is in there somewhere?) I suggest to include the same headings "Themes" as we have in the Level A data in the Virtual Water Science > Lab under "Collect input data". They feel natural to a hydrological modeler."*

Currently those categories are assigned to Level A Data in the Meta-Data Repository:
- Land-use
- Modelled river discharge
- Observed river discharge
- PotEvapo
- Precipitation
- Soils
- Subbasins
- Temperature

Those categories are also considered in the Expert GUI Catalogue:

![categories-expert-gui](https://cloud.githubusercontent.com/assets/1788226/6349839/c2f4ef1e-bc2e-11e4-8a25-f0b64f723e5b.png)

**Comment by p-a-s-c-a-l** [comment]
D4.3 metadata (data used by products ) is not in the database (needs be there or be in google drive).  Kees and @esafa to fix using metadata wizard.

**Comment by p-a-s-c-a-l** [comment]
see https://docs.google.com/spreadsheets/d/1Gun_owsjd9ICf9aEkjO37jORemq0z4VJG3IbuJorDwA/edit#gid=366761149

**Comment by esafa** [comment]
Yes D4.3 is well underway. Kees and me will do the final checks next week.
After that we will try to import it.
//Esa


On Wed, Apr 1, 2015 at 3:51 PM, Pascal Dihé <notifications@github.com>
wrote:

> see
> https://docs.google.com/spreadsheets/d/1Gun_owsjd9ICf9aEkjO37jORemq0z4VJG3IbuJorDwA/edit#gid=366761149
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/53#issuecomment-88487733>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
Status? See also https://github.com/switchonproject/cids-custom-switchon/issues/110 and https://github.com/switchonproject/cids-custom-switchon/issues/105

**Comment by esafa** [comment]
The D4.3 is fully included into the batches provided by Emma and Viktor.
Most of it is already imported.


On Wed, Jul 15, 2015 at 11:53 AM, Pascal Dihé <notifications@github.com>
wrote:

> Status? See also switchonproject/cids-custom-switchon#110
> <https://github.com/switchonproject/cids-custom-switchon/issues/110> and
> switchonproject/cids-custom-switchon#105
> <https://github.com/switchonproject/cids-custom-switchon/issues/105>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/53#issuecomment-121559814>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
done
