### ISSUE TITLE
User story René 02

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/sip-html5#6]
![*René](https://avatars3.githubusercontent.com/u/9919?v=3&s=64) **René**:

> As a hydrological modeler, I would like to be able to differentiate between observations and products (typically other model results) in the data listed in the SIP, so I do not accidentally evaluate my model against other model results with unknown errors.

**Comment by schlob** [comment]
OK, seems rather important:-)

For me this maps to: The meta data set needs to contain the information to distinguish between observation and product. This can either be reflected through a property of the meta data schema or
through a Tag. If it is central it would go in the meta data schema if not it would be rather 2 tags.

No problem. 
As a comment: this kind of User Story is good to collect info about specific aspects of a system. That can be directly implemented under the assumption that the general Application (or the concept) exists already. However, as we are starting right now with the development it does not help much now (but only in later stages)

**Comment by rcapell** [comment]
i agree that this won't be the first issue to tackle.
