### ISSUE TITLE
Improve SIP Landing Page

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/sip-html5#61]
Changes in texts need in [SIP landing-page](http://www.water-switch-on.eu/sip.html) to make it more understandable for the external scientists.  What do we offer… Search/find, download etc.. Goal of tool.. perhaps screenshot? Links to the API on the left side. @GBoot and Anna.

No info on Browser compatibility.  Some minor GUI issues in IE11.  Action: add text to landing page. “The HTML5-client was tested on Chrome version xx.yy and Android. You may encounter issues with other browsers….” @GBoot and Anna

For other information / links that could be put on the landing pages see also 
- https://github.com/switchonproject/sip-html5/issues/44#issuecomment-78220377
- https://github.com/switchonproject/sip-html5/issues/45#issuecomment-78220232

**Comment by p-a-s-c-a-l** [comment]
Suggested named for the HTML5-GUI tool:
- EXODUS (EXplore Open Data Using Searches)
- HEXODUS (Hydrological Explore....)
- XeDUHEX 
- ...

**Comment by esafa** [comment]
The landing page changed but it still contains a lot of unexplained abbreviations and techobabble.. the info is not in the language of hydrologists.

Perhaps rene, remko duro can come up with a more easy to understand text.

**Comment by p-a-s-c-a-l** [comment]
done
