### ISSUE TITLE
Usability-Testing

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/sip-html5#62]
We also have access to close to hundred of "new fresh scientist-users" that can do some quick 10 minute usability-testing and give their fresh first impressions (basically reading the userstory and let the new users try to do it with the client). Should be do some broader user testing now?  @esafa makes tests at SMHI. @GBoot initiate test at Deltares… report using mp4-videos of user using the tool.

**Comment by esafa** [comment]
They (two persons) have done the usability testing at SMHI. I will ask for
the video capture files. I dont know what the status is on the Deltares
tests.


On Wed, May 20, 2015 at 8:54 AM, Pascal Dihé <notifications@github.com>
wrote:

> Closed #62 <https://github.com/switchonproject/sip-html5/issues/62>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/62#event-309220589>.
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)
