### ISSUE TITLE
Improve spatial extent of resources in the Meta-Data Repository

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/sip-html5#63]
SHOWSTOPPER (at least confusing for external visitors). spatialExtent is often only available on a very coarse level (Europe or World), even for data sets for specific countries. @rcapell, @rcnijzink,  @duropa to suggest a solution. One solution is to define the actual points for datasets with false worldboxes. The useless worldboxes should possibly be not shown… 

See also https://github.com/switchonproject/cids-custom-switchon-server/issues/32

**Comment by p-a-s-c-a-l** [comment]
I've assigned polygons of European countries to "bathing water report" and "airbase" resources:

![european-countries](https://cloud.githubusercontent.com/assets/1788226/6620174/91210538-c8cf-11e4-9b25-ffc76e64f7ee.png)

If you identify further finer grained spatial extends for some resources, pleas let me know.

**Comment by p-a-s-c-a-l** [comment]
I added points for "EOBS predefined subsets in ASCII general":

![ecad_prec_stations](https://cloud.githubusercontent.com/assets/1788226/6737097/aeb90e84-ce69-11e4-808e-639d8f210f8a.png)

**Comment by p-a-s-c-a-l** [comment]
I added polygons for "ECRINS_lakes":

![ecrins_lakes](https://cloud.githubusercontent.com/assets/1788226/6737112/c319bcf2-ce69-11e4-9309-125c3c141920.png)

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by esafa** [comment]
the summerworkers have prepared some 10 GB of WKT-polygons to resolve the
"worldbox problem".. these are in the process of being uploaded.


On Mon, Jul 6, 2015 at 10:41 AM, Pascal Dihé <notifications@github.com>
wrote:

> Closed #63 <https://github.com/switchonproject/sip-html5/issues/63>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/63#event-348383963>.
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
@esafa @rcapell 
I wonder whether these CLC datasets are really relevant for hydrologists?
- Sport and leisure facilities
- Mineral extraction sites
- etc

**Comment by esafa** [comment]
Heavy metal concentration in water might be influenced by mineral
extraction. Wasnt EMVIS is doing stuff with heavy metals I think?



On Tue, Jul 7, 2015 at 9:13 AM, Pascal Dihé <notifications@github.com>
wrote:

> @esafa <https://github.com/esafa> @rcapell <https://github.com/rcapell>
> I wonder whether these CLC datasets are really relevant for hydrologists?
>
>    - Sport and leisure facilities
>    - Mineral extraction sites
>    - etc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/63#issuecomment-119097415>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)
