### ISSUE TITLE
Public Beta Release

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/sip-html5#66]
Create a Public Beta Release for EGU2015 (April 12-17). 
Depends on https://github.com/switchonproject/cids-custom-switchon-server/issues/34

**Comment by p-a-s-c-a-l** [comment]
Change endpoint to: https://github.com/switchonproject/cids-custom-switchon/wiki/SIP-Releases#cids-server-rest--legacy-base-for-sip-html5-client-bases-on-sip-expert-server

**Comment by p-a-s-c-a-l** [comment]
Clickable buttons (e.g. Categories) should not be grey.

**Comment by p-a-s-c-a-l** [comment]
@gboot @esafa @schlob 
BETA Release for testing is available here: http://www.water-switch-on.eu/sip-webclient/sip-beta

Please report any bugs / ui issues in github and label those as SHOWSTOPPER that **must to be fixed** by Friday before EGU 2015.

**Comment by esafa** [comment]
thanks.. I will talk to the test team tomorrow.


On Tue, Apr 7, 2015 at 5:35 PM, Pascal Dihé <notifications@github.com>
wrote:

> @gboot <https://github.com/gboot> @esafa <https://github.com/esafa>
> @schlob <https://github.com/schlob>
> BETA Release for testing is available here:
> http://www.water-switch-on.eu/sip-webclient/sip-beta
>
> Please report any bugs / ui issues in github and label those as
> SHOWSTOPPER that *must to be fixed* by Friday before EGU 2015.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/66#issuecomment-90611994>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
new release should be made when https://github.com/switchonproject/cids-custom-switchon-server/issues/36 is resolved and new sever release is deployed.

**Comment by p-a-s-c-a-l** [comment]
done
