### ISSUE TITLE
User story Remko 01

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/sip-html5#7]
![Remko](https://avatars3.githubusercontent.com/u/9919?v=3&s=64) **Remko**:

> As hydrological modeler, I would like two find different data types (like meteo and discharge), which are spatially correlated (in other words, in the same catchment), so I can directly see if all the data for my model is available.

**Comment by schlob** [comment]
I interprete this that you want to perform a spatial search using e.g. a catchment polygon as search geometry and you want to be able to filter the results according to their type (e.g. added to the meta data as tag)

This is in principal what Pascal's Mockup is about. However, this the major part of the software to be developed, meaning this is "epic" in Esa's sense. I would expect to have this in late Summer.
