### ISSUE TITLE
User story Remko 02

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/sip-html5#8]
![Remko](https://avatars3.githubusercontent.com/u/9919?v=3&s=64) **Remko**:

> As a simple user, I want to reach the place where I can actually get the data quickly, so I don’t have to search for a second time.

**Comment by p-a-s-c-a-l** [comment]
![Esa](https://avatars2.githubusercontent.com/u/6159801?v=3&s=64) **Esa**:

>Quick navigation is an important aspect of any GUI, but quickly reaching different parts is more a design issue rather than a user story that describes what a “simple user” really needs.

**Comment by p-a-s-c-a-l** [comment]
![René’](https://avatars3.githubusercontent.com/u/9919?v=3&s=64) **René**:

> I think I understand what Remko means, one often is confronted with portals which show metadata, but the actual access point is very well hidden or even on another database

**Comment by schlob** [comment]
OK, for me this maps to: A meta data set shall always contain a direkt link to the acutal data.

This is already modelled that way in the SIM (the underlying data model of the SIP)
