### ISSUE TITLE
no results shown for AMSR-E keyword search 

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#87]
Starting the beta
Selecting keyword AMSR-E
Changing max number of results to be presented to 5000
Start search..
Wait a few minutes (progress bar goes to 50% and says "SWITCH-ON Metadata Repository is under heavy load, please wait for the search to continue"
Wait a bit more and the search bar dissappears
A green boxs says "collecting  xxx of 3394 resources" .. xxx is a number that counts up 
the number comes up to 3394 and the search is completed.. 
but no results are shown.

![image](https://cloud.githubusercontent.com/assets/6159801/7028158/55f607a8-dd54-11e4-86d2-76686bfeaf45.png)

**Comment by esafa** [comment]
@p-a-s-c-a-l   : dont think i can assign labels.. these options are grey to me in github.

**Comment by p-a-s-c-a-l** [comment]
> Changing max number of results to be presented to 5000

How? 50 is the Max. Search Results that can safely be handled by the client and you aren't even able to select a number > 50 in filter options.

**Comment by esafa** [comment]
I just entered 5000 manually... and it did the search.


On Tue, Apr 7, 2015 at 9:15 PM, Pascal Dihé <notifications@github.com>
wrote:

> Changing max number of results to be presented to 5000
>
> How? 50 is the Max. Search Results that can safely be handled by the
> client and you aren't even able to select a number > 50 in filter options.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/87#issuecomment-90704005>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by esafa** [comment]
latest chrome version


On Tue, Apr 7, 2015 at 9:16 PM, Dr Falkenroth <nospam@falkenroth.se> wrote:

> I just entered 5000 manually... and it did the search.
>
>
> On Tue, Apr 7, 2015 at 9:15 PM, Pascal Dihé <notifications@github.com>
> wrote:
>
>> Changing max number of results to be presented to 5000
>>
>> How? 50 is the Max. Search Results that can safely be handled by the
>> client and you aren't even able to select a number > 50 in filter options.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/switchonproject/sip-html5/issues/87#issuecomment-90704005>
>> .
>>
>
>
>
> --
> Esa Falkenroth
> mobile: 070-666-14-14 (intl +46706661414)
> work: 011-4958298 (intl +46114958298)
> skype: Esa.Falkenroth
> email: nospam@falkenroth.se (for business mail)
> email: esa@falkenroth.se (for private mail)
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by esafa** [comment]
the way to reproduce the problem is to click in the numeric box where you
set the upper limit of returned data and then type 5000 on the keyboard..
after that you press the search "looking glass" button near the numeric box.


On Tue, Apr 7, 2015 at 9:17 PM, Dr Falkenroth <nospam@falkenroth.se> wrote:

> latest chrome version
>
>
> On Tue, Apr 7, 2015 at 9:16 PM, Dr Falkenroth <nospam@falkenroth.se>
> wrote:
>
>> I just entered 5000 manually... and it did the search.
>>
>>
>> On Tue, Apr 7, 2015 at 9:15 PM, Pascal Dihé <notifications@github.com>
>> wrote:
>>
>>> Changing max number of results to be presented to 5000
>>>
>>> How? 50 is the Max. Search Results that can safely be handled by the
>>> client and you aren't even able to select a number > 50 in filter options.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/switchonproject/sip-html5/issues/87#issuecomment-90704005>
>>> .
>>>
>>
>>
>>
>> --
>> Esa Falkenroth
>> mobile: 070-666-14-14 (intl +46706661414)
>> work: 011-4958298 (intl +46114958298)
>> skype: Esa.Falkenroth
>> email: nospam@falkenroth.se (for business mail)
>> email: esa@falkenroth.se (for private mail)
>>
>
>
>
> --
> Esa Falkenroth
> mobile: 070-666-14-14 (intl +46706661414)
> work: 011-4958298 (intl +46114958298)
> skype: Esa.Falkenroth
> email: nospam@falkenroth.se (for business mail)
> email: esa@falkenroth.se (for private mail)
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by esafa** [comment]
https://www.youtube.com/watch?v=-KYk86wsbAk&feature=youtu.be&hd=1

**Comment by esafa** [comment]
After some 10-15 minutes the "collection" finished and the client showed the results so it actually works with 3394 rows returned to the client. Not much memory consumption in chrome.... As you can see in the vid below the download button is sluggish.

http://youtu.be/wK1ATo04bME?hd=1
