### ISSUE TITLE
Non-ISO date format in search results (not showstopper)

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#88]
The dates are presented as MM.DD.YYYY . I would have expected dates to be presented according to some wellknown/established standard. 

ISO would be one of the most attractive standards for dates since it makes lexicographic sorting produce lists in correct time order.

![image](https://cloud.githubusercontent.com/assets/6159801/7028464/445c21a6-dd56-11e4-97d7-8c96782d0e5a.png)

**Comment by p-a-s-c-a-l** [comment]
resolved in #109
