### ISSUE TITLE
Performance in search (not showstopper)

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#89]
I am measuring about 3-7 rows (datasets) per second. On a fairly new i5 laptop with plenty of free memory I would have expected somewhere around 1000 rows per second.

**Comment by p-a-s-c-a-l** [comment]
1000 rows per second?! Calling a **webservice* not a database backend?

**Comment by esafa** [comment]
Yes.. A webservice can easily return 1000 rows per second if the return data is aggregated.
