### ISSUE TITLE
User story Duro 01

### ISSUE THREAD

**Issue by duropa** [switchonproject/sip-html5#9]
as an unexperienced user-story writer and a command-line user, i would like to perform different searches from commandline, having output in (somehow organised) text file.

**Comment by p-a-s-c-a-l** [comment]
Imho a CLI is beyond the the scope of the SIP **GUI**. However, the SIP consists also of a server-side part that will offer simple RESTful APIs, e.g. [for searching for resources](https://github.com/switchonproject/sip-html5/wiki/Universal-Search-API-Specification#universal-search-api). These APIs can also be queried from the command line, e.g. with _curl_. The API returns resources as JSON objects (structured text).

Here is a short demo videos of the SIP RESTful API: https://www.youtube.com/watch?v=1vWpg0tEeeg

This API is developed in parallel to the SIP HTML5 GUI. Once a first version is implemented, I'll publish the API endpoint and you can test it from the command line.

**Comment by esafa** [comment]
At this point it would be best to focus on what the users need (not the
technical solutions that meet the need. CLI,  Technical solutions such as
API, GUI, CLI have no place in a good user-story. Please keep to the
format:

AS <some role>, I NEED <describe what you need>, SO I can <what goal is
accomplished>

Later on... we will discuss how we can fulfill the need. At this time, it
will be very relevant to talk about API, GUI and/or CLI, but lets start
with that the user group NEEDs... (essentially the "why" and "what" part
and we will deal with "how" later on ).

Cheers,
//Esa


On Tue, Jan 20, 2015 at 9:27 AM, Pascal Dihé <notifications@github.com>
wrote:

> Imho a CLI is beyond the the scope of the SIP *GUI*. However, the SIP
> consists also of a server-side part that will offer simple RESTful APIs,
> e.g. for searching for resources
> <https://github.com/switchonproject/sip-html5/wiki/Universal-Search-API-Specification#universal-search-api>.
> These APIs can also be queried from the command line, e.g. with *curl*.
> The API returns resources as JSON objects (structured text).
>
> Here is a short demo videos of the SIP RESTful API:
> https://www.youtube.com/watch?v=1vWpg0tEeeg
>
> This API is developed in parallel to the SIP HTML5 GUI. Once a first
> version is implemented, I'll publish the API endpoint and you can test it
> from the command line.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/9#issuecomment-70619713>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)
