### ISSUE TITLE
map button dissappears at some screen sizes (minor bug, no showstop)

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#93]
![image](https://cloud.githubusercontent.com/assets/6159801/7136833/c232d9cc-e2b4-11e4-8972-54b00ddd5eb0.png)

not responsive design.

minor issue since most use browsers with larger screens with full-screen mode (not resized windows).

**Comment by p-a-s-c-a-l** [comment]
resolved in https://github.com/switchonproject/sip-html5/issues/100
