### ISSUE TITLE
Hide unused keywords in search filter

### ISSUE THREAD

**Issue by rcapell** [switchonproject/sip-html5#98]
In the scroll menu for CUAHSI keywords, many keywords have no data. These should be removed from the menu until data is added, in order not to annoy users not finding data

Berit, René

**Comment by esafa** [comment]
That is a good idea.. I think I posted that earlier too..

Basically build the scroll menu by looking for unique X-CUAHSI keywords
that ALREADY exist for some dataset in the database.

On Tue, Jun 30, 2015 at 6:10 PM, rcapell <notifications@github.com> wrote:

> In the scroll menu for CUAHSI keywords, many keywords have no data. These
> should be removed from the menu until data is added, in order not to annoy
> users not finding data
>
> Berit, René
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/98>.
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
OK, will do.

**Comment by p-a-s-c-a-l** [comment]
@esafa @rcapell 

ATM, this list would show the following (X-)CUAHSI keywords:
- Biomass, zooplankton
- Level, stream
- Optical, water
- Volume
- Water body
- Water body, aquifer
- Water body, river

**Comment by esafa** [comment]
Yes.. but much more is incoming from Emma and Victor (some are already in
the production database).


On Wed, Jul 1, 2015 at 11:31 AM, Pascal Dihé <notifications@github.com>
wrote:

> @esafa <https://github.com/esafa> @rcapell <https://github.com/rcapell>
>
> ATM, this list would show the following (X-)CUAHSI keywords:
>
>    - Biomass, zooplankton
>    - Level, stream
>    - Optical, water
>    - Volume
>    - Water body
>    - Water body, aquifer
>    - Water body, river
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/98#issuecomment-117561265>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by rcapell** [comment]
is this a dynamic thing or do you have to manually update the visible categories when new data sets are added?

**Comment by p-a-s-c-a-l** [comment]
@rcapell ATM it's a static list but I'll make it dynamic.

**Comment by rcapell** [comment]
thanks!

**Comment by p-a-s-c-a-l** [comment]
@rcapell @esafa 

The functionality is implement and can be tested in the latest development snapshot: http://switchon.cismet.de/sip-snapshot/

Please note, that this DEV snapshot of the SIP is not connected to the live MetaDB but an internal backup db. Thus ,the X-CUAHSI keywords used by the summer worker team are not yet available. 

![x-cuahsi](https://cloud.githubusercontent.com/assets/1788226/8500647/380468fa-219e-11e5-8896-e1570094779a.png)

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by esafa** [comment]
nice indeed.

On Mon, Jul 6, 2015 at 2:39 PM, Pascal Dihé <notifications@github.com>
wrote:

> Closed #98 <https://github.com/switchonproject/sip-html5/issues/98>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/98#event-348572481>.
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)
