### ISSUE TITLE
more frequent updates of public sip on the portal

### ISSUE THREAD

**Issue by rcapell** [switchonproject/sip-html5#99]
There are frequent workshops and conferences where we try to promote the SWITCH-ON work and portal where also the sip could be promoted. 
It would for instance be nice if the public sip client could be updated to the latest version before the CUAHSI workshop on 13th July in the US.

Berit, René

**Comment by p-a-s-c-a-l** [comment]
OK, I'll make a new release before the workshop that support https://github.com/switchonproject/cids-custom-switchon/issues/129 and https://github.com/switchonproject/sip-html5/issues/98

@emmaladolphi 
Please note, before the CUAHSI workshop we'll should have a considerable amount of resources tagged with (X)CUAHSI keywords ;-)

**Comment by p-a-s-c-a-l** [comment]
Done. https://github.com/switchonproject/sip-html5/releases/tag/sip-v0.6-beta
